# Generated by Django 4.1 on 2022-09-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_key', models.CharField(max_length=50)),
                ('personal_name', models.CharField(max_length=100)),
                ('view_count', models.IntegerField(default=1)),
            ],
        ),
    ]
